#!/usr/bin/env python3

import subprocess
import datetime

pr = subprocess.Popen(['git', 'rev-parse', 'HEAD'], stdout=subprocess.PIPE)
git_hash, err = pr.communicate()

if pr.returncode:
    raise RuntimeError('git failed')

git_hash = git_hash.strip()
date_str = datetime.datetime.now().strftime("%Y-%m-%d")

version_string = '%s git %s' % (date_str, git_hash[:10])

fd = open("version.c", 'w')
fd.write('#include "version.h"\n')
fd.write('\n')
fd.write('const char software_version_string[] PROGMEM = "%s";\n' % version_string)
